# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(891, 550)
        self.table = QtWidgets.QTableWidget(Form)
        self.table.setGeometry(QtCore.QRect(10, 40, 871, 501))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.addBtn = QtWidgets.QPushButton(Form)
        self.addBtn.setGeometry(QtCore.QRect(10, 10, 151, 28))
        self.addBtn.setObjectName("addBtn")
        self.changeBtn = QtWidgets.QPushButton(Form)
        self.changeBtn.setGeometry(QtCore.QRect(170, 10, 151, 28))
        self.changeBtn.setObjectName("changeBtn")
        self.output = QtWidgets.QLabel(Form)
        self.output.setGeometry(QtCore.QRect(330, 10, 201, 21))
        self.output.setText("")
        self.output.setObjectName("output")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.addBtn.setText(_translate("Form", "Добавить элемент"))
        self.changeBtn.setText(_translate("Form", "Изменить элемент"))
